FROM ruby:3.3.8

# 基本パッケージインストール
RUN apt-get update -qq && \
    apt-get install -y \
      nodejs \
      npm \
      postgresql-client && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Gemfile関連
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリケーションファイル
COPY . .

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]